# -*- coding: utf-8 -*-
"""erome-scapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foFysQKVddi1kMqGU-rY00Ds3hZiQvZ7
"""

import os
from google.colab import files

# Install eromedownloader
!pip install eromedownloader

# Prompt user for Erome URL
url = input("Enter the Erome album URL to scrape: ")

# Run download command with user-provided URL
!python -m eromedownloader --url {url} --path /content/erome_album

# Check downloaded files
!ls -l /content/erome_album

# Zip and download
!zip -r /content/erome_album.zip /content/erome_album
files.download('/content/erome_album.zip')

